// <auto-generated />
using CarrinhoComprasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarrinhoComprasAPI.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20250320214117_UpdateDatabaseVer1_1")]
    partial class UpdateDatabaseVer1_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CarrinhoComprasAPI.Models.CarrinhoCompra", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTransacao"));

                    b.Property<string>("CdEmpresa")
                        .HasColumnType("longtext");

                    b.Property<string>("NmCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("QtdProduto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipPagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("VlTotal")
                        .HasColumnType("longtext");

                    b.HasKey("IdTransacao");

                    b.ToTable("CarrinhoCompra");
                });

            modelBuilder.Entity("CarrinhoComprasAPI.Models.Cliente", b =>
                {
                    b.Property<int>("CdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CdUsuario"));

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("DtCadastro")
                        .HasColumnType("longtext");

                    b.Property<string>("DtNascimento")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("NmUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("PassWd")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("TipCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("TipUsuario")
                        .HasColumnType("longtext");

                    b.HasKey("CdUsuario");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("CarrinhoComprasAPI.Models.DadosPagamento", b =>
                {
                    b.Property<int>("CdCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CdCard"));

                    b.Property<string>("ApelidoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("CVV")
                        .HasColumnType("longtext");

                    b.Property<string>("DtValidade")
                        .HasColumnType("longtext");

                    b.Property<string>("NmCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumCard")
                        .HasColumnType("longtext");

                    b.HasKey("CdCard");

                    b.ToTable("DadosPagamento");
                });

            modelBuilder.Entity("CarrinhoComprasAPI.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("NmBairro")
                        .HasColumnType("longtext");

                    b.Property<string>("NmCidade")
                        .HasColumnType("longtext");

                    b.Property<string>("NmEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("NumCasa")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.HasKey("IdEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("CarrinhoComprasAPI.Models.Fornecedor", b =>
                {
                    b.Property<int>("IDFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDFornecedor"));

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("CtoFornecedor")
                        .HasColumnType("longtext");

                    b.Property<string>("DtCadastro")
                        .HasColumnType("longtext");

                    b.Property<string>("NmFornecedor")
                        .HasColumnType("longtext");

                    b.Property<string>("TipFornecedor")
                        .HasColumnType("longtext");

                    b.HasKey("IDFornecedor");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("CarrinhoComprasAPI.Models.Logs", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DtLog")
                        .HasColumnType("longtext");

                    b.Property<string>("HrLog")
                        .HasColumnType("longtext");

                    b.HasKey("IdLog");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("CarrinhoComprasAPI.Models.Produtos", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<int>("AnoProduto")
                        .HasColumnType("int");

                    b.Property<string>("DtCadastro")
                        .HasColumnType("longtext");

                    b.Property<string>("MarcaProduto")
                        .HasColumnType("longtext");

                    b.Property<string>("ModeloProduto")
                        .HasColumnType("longtext");

                    b.Property<string>("NmProduto")
                        .HasColumnType("longtext");

                    b.Property<double>("PrecoProduto")
                        .HasColumnType("double");

                    b.Property<double>("QntEstoque")
                        .HasColumnType("double");

                    b.Property<string>("TipPeça")
                        .HasColumnType("longtext");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
